name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        sudo apt install ruby-full build-essential zlib1g-dev
        gem install jekyll bundler
        bundle install
        bundle exec jekyll build
        echo "${{ secrets.DOCKERPW }}" | docker login -u "jasonjcrevier"
        docker build -t jasoncrevier_website:latest .
        docker tag jasoncrevier_website jasonjcrevier/jasoncrevier_website
        docker push jasonjcrevier/jasoncrevier_website
